apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u9kg24smx-python 
  janus-idp.io/tekton: u9kg24smx-python
  backstage.io/kubernetes-id: u9kg24smx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u9kg24smx-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  