apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u9kg24smx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u9kg24smx-python 
  name: u9kg24smx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u9kg24smx-python 
