apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u9kg24smx-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fdfd8ff0d0.qsqc.p3.openshiftapps.com/rhtap/rhtap-qe:7f80c0da7451ee17a9d6e54dcd6c2689b24c13f0@sha256:8c23baa1cae505c3f4312c9de259e0e1773b1fb2650daf0669718309a9e0612a
          name: container-image
